Fixed "/Users/runner/work/SharpSDL3/SharpSDL3/tests/SharpSDL3.Tests/NativeSurfaceTests.cs(27,87): error CS0117: 'PixelFormat' does not contain a definition for 'Rgb888' [/Users/runner/work/SharpSDL3/SharpSDL3/tests/SharpSDL3.Tests/SharpSDL3.Tests.csproj]"; changed to Bgra8888 for testing